name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: client/pnpm-lock.yaml
          
      - name: Install dependencies
        working-directory: ./client
        run: pnpm install
        
      - name: Run tests with coverage
        working-directory: ./client
        run: pnpm test:coverage
        
      - name: Build application
        working-directory: ./client
        run: pnpm build
        
      - name: Install Playwright browsers
        working-directory: ./client
        run: pnpm exec playwright install --with-deps
        
      - name: Run E2E tests
        working-directory: ./client
        run: pnpm test:e2e
        
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: client/coverage
          
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report